#!/bin/bash
. xivo_versions_data

gpg_signing_key=DFB0B268
debian_version=jessie

commit() {
    local message=$1
    git commit -a -m "$message" > /dev/null
    git push > /dev/null
}

create_pxe_config_file() {
    local archive_config_file="sources/debian-pxelinux/archive/archive-xivo.cfg"
    cat pxe.head > $archive_config_file
    for version in $xivo_versions; do
        label="xivo-$version"
        class=$label
        cat >> $archive_config_file << EOF
label $label-amd64
    menu label $label (amd64)
    kernel fai-linux-$debian_version-64
    append initrd=fai-initrd-$debian_version-64 rw auto=true url=$mirror priority=critical locale=en_US.UTF-8 interface=auto netcfg/dhcp_timeout=60 classes=debug,$class hostname=xivo --
label $label-amd64-raid
    menu label $label (amd64) with software RAID
    kernel fai-linux-$debian_version-64
    append initrd=fai-initrd-$debian_version-64 rw auto=true url=$mirror priority=critical locale=en_US.UTF-8 interface=auto netcfg/dhcp_timeout=60 classes=debug,$class,raid hostname=xivo --
label $label-i386
    menu label $label (i386)
    kernel fai-linux-$debian_version
    append initrd=fai-initrd-$debian_version rw auto=true url=$mirror priority=critical locale=en_US.UTF-8 interface=auto netcfg/dhcp_timeout=60 classes=debug,$class hostname=xivo --
EOF
    done
    cat pxe.tail >> $archive_config_file
    cd "sources/debian-pxelinux" > /dev/null
    commit "add new archive entry"
    cd - > /dev/null
}

create_debian_installer_classes() {
    cd "sources/debian-installer" > /dev/null
    for version in $xivo_versions; do
        template="$debian_version/classes/xivo-template"
        directory="$debian_version/classes/xivo-$version"
        if [ ! -d $directory ]; then
            echo "xivo-$version does not exist, creating it"
            rsync -av $template/ $directory/ > /dev/null
            sed -i "s/xivo-template/xivo-$version/" $directory/postinst_script
            git add $directory > /dev/null
            commit "add archive xivo-$version"
        fi
    done
    cd - > /dev/null
}

reverse() {
    echo $@ | tac -s' '
}

create_mirror_distribution_file() {
    distrib_config_file="sources/debian-repo-archive/distributions"
    sed s/__gpg_signing_key__/$gpg_signing_key/g distributions.head > $distrib_config_file
    for version in $(reverse $xivo_versions); do
        cat >> $distrib_config_file << EOF
Origin: xivo.io
Label: xivo-$version
Suite: xivo-$version
Codename: xivo-$version
#Update: xivo-five
Architectures: i386 amd64 source
Components: main
Description: Archive xivo-$version
SignWith: $gpg_signing_key

EOF
    done
    cd sources/debian-repo-archive > /dev/null
    commit "add archive mirror"
    cd - > /dev/null
}

echo "Creating PXE configuration file"
create_pxe_config_file
echo "Creating PXE classes"
create_debian_installer_classes
echo "Creating mirror configuration file"
create_mirror_distribution_file
