#!/bin/bash -e

get_repo() {
    if [ -d debian-repo-archive ]; then
        cd debian-repo-archive && git pull
        cd -
    else
        git clone ssh://git@github.com/wazo-platform/debian-repo-archive
    fi
}

mkdir -p sources
cd sources
get_repo
