#!/bin/bash
repositories="debian-installer debian-pxelinux manage_xivo_archive"
url="ssh://gitolite@git.xivo.io/official"

if [ ! -d sources ]; then
    mkdir sources
fi

get_repo() {
    if [ -d $repository ]; then
        cd $repository && git pull
        cd -
    else
        git ls-remote $url/$repository &> /dev/null
        if [ $? -ne 0 ]; then
            "You cannot clone repository, abording"
            exit 1
        fi
        echo "get $repository"
        git clone $url/$repository
    fi
}

cd sources
for repository in $repositories; do
    get_repo $repository
done
